<?php

namespace App\Admin\Controllers\Auth;

use App\Admin\Controllers\Controller;
use App\Admin\Services\Auth\AuthService;
use Exception;
use \Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class AuthController extends Controller
{
    /**
     * Show the login page.
     *
     * @return Redirector|RedirectResponse|View|Factory
     */
    public function index(Request $request)
    {
        if (AuthService::check()) {

            $prefix = config('admin.route.prefix');

            // redirect to root path
            return redirect('/' . $prefix);
        }

        $data = [];
        if(config('admin.auth.captcha')) {
            $captcha = self::captcha();

            $request->session()->put('captcha', $captcha->code);

            $data = [
                'captcha' => 'data:image/jpeg;base64,' . base64_encode($captcha->data)
            ];
        } 

        return admin_view('auth/login', $data);
    }

    public static function captcha(int $length = 4, int $width = 150, int $height = 50, int $size = 24, string $font = ''): object
    {
        if(!extension_loaded('gd')) {
            throw new Exception('Required GD library is missing');
        }

        if($length <= 0) {
            throw new Exception('Length must be greater than 1');
        }

        // the `ActionJackson` font
        if($font == '') {
            $font = storage_path('admin/ActionJackson.ttf');
            $data = <<<BASE64
AAEAAAAPAIAAAwBwT1MvMn2PVggAAAD8AAAAVmNtYXAAgACOAAABVAAAADxjdnQguzK/FgAAAZAA
AAAyZnBnbYMzwk8AAAHEAAAAFGdseWbBU94zAAAB2AAASSRoZG148WNQIAAAS1AAAALIaGVhZM5G
mpAAAE4YAAAANmhoZWEGgAKxAABOUAAAACRobXR4YOICwgAATnQAAACga2Vybv/SADkAAE8UAAAA
HmxvY2FiY1AGAABK/AAAAFJtYXhwAPsEnwAATzQAAAAgbmFtZT7oUogAAE9UAAAC0nBvc3T/fgAU
AABSKAAAACBwcmVw6s/YqAAAUkgAAABrAAECnAGQAAUAAAK8AooAAACPArwCigAAAcUAMgEDAAAA
AAQAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAEZyb2cAQAAwAFoDVf9cAAADVQCkAAAAAQAAAAAAAAAA
AAIAAAAAAAAAFAADAAEAAAAUAAQAKAAAAAYABAABAAIAOQBa//8AAAAwAEH////U/80AAQAAAAAA
AAALAwkAIQAYABsAIwAcAJsAPQBjAS0BaQEQAdgAuAGyAN4A+QHVWnJaclpyWnIABAAGAABAAQAs
dkUgsAMlRSNhaBgjaGBELQAGAAYAEgI8AwMAGwAlAD0ATQBcAGcAeUA1AWhoQGkAZF4kHmZkXSMe
VwJIT04CPhwDADQCDCYCIGICSDoFCFMFTC4EElkERBIBCAABDEZ2LzcYAD8/L/0Q/S/9EP0BL/0v
/S/9L/0v/TwQ/S4uLi4uAC4uLi4xMAFJaLkADABoSWhhsEBSWDgRN7kAaP/AOFkBFAcGBwYHBiMi
JyY1NDc2NzYzMhcWFxYXFhcWBzQnFhUUBhUXNic0JyYnJicmIyIHBgcGFRQXFhcWMzI3NicUBwYH
BiMiJyY1NDc2MzIDNTQnJiMiBwYVFDMyNzYvAQYHBhUUFyY1NAI8BQgBDjo+VKBbUygzayUCeUUN
GS8REwcLGjkiCBgHPgUHAQc8P1GtHQELCRkmIzRPgzMkRw0RFBk4UCYcGyNBlioSDgg2JBtUJRQQ
kxAeCAMYAgEqDxYgBVU6P3RqpX9ZcB0JPA8dNiInQ2JM5U6JaRJHEwIrXRspOAxTQETXDSIdEng5
WSY3ZEe3MVVlExluTmNLP1L+o6cPSQtqUkaJMCXwAgwfDTNFLhgWXwAABAApAAYCDwMMAEUAWQCK
AJMAk0BCAZSUQJUAjnFtZF5cWVE+IR+RfmtPTkdGPBcPJg4aAAJaeQMadQMdSwM4WgOOj2ADWGID
VEAFBJGDBQsvAQsAAQ9Gdi83GAA/PxD9PC/9AS/9L/0vPP0v/S/9L/0Q/RD9Li4uLi4uLi4uLgAu
Li4uLi4uLi4uLjEwAUlouQAPAJRJaGGwQFJYOBE3uQCU/8A4WSUUBwYjIgYHBgcGByInJjU0NzY3
NjM2NTQmNTQ2NTQnBgcmJy4BNTQ3Njc2Nz4BMzIXFhcWFRQWFRQHBhcWFzYzMhcWFxYnNRQnJjU0
Jj0BNCcUBhUUFxYfAiYnBiMiJwI3JiMiBgcGBwYHFhc2NzYzMBcWFRQHBgcWDwEGBxYXMhYzMjc2
NzY3Njc0JicHFBc0JgIPFAokCB4FIEAzgwhCGQsEPDgOBAMJAwQNEiQPOiUsAggOCJIPDhgVBAgC
AgIBAQYxBREIJAkDlwICBxgCBQUEEV0EBCs9FwIMARIJEV4KFRUZFxImEBEYCwoMBAUBAgMIYyEH
DgMNBCEzSwkuLTZOEAIBFwRKHAgEBwECBgcFSUMfDgwDBwcDEQsrAxllGhERCAgIEwhJDgc7RgMR
FAINJSIRJ10ZbxkQJiATHBkFBh4uE2ANCSEcWSCLH1kDIg49D090Xl8KeiJCBzUBG8cEDAUkJSsa
GC4QERgCCoIaKjcNJUYGDAEeOwIGCQECAwQ8CA8DSxAUDjsABQAhACICRwL2AEAASgCHAJIAmwCu
QFQBnJxAnQCbkYxsSSCTd2lLRjaIAnFYAgAaAnGZAw+OAyRBA3FgAy+FAgUDB0QFbhwFboMFCYB+
fAN7BQw9BUtLBDo4NjoEl1RSUAROYwQsLAkBJEZ2LzcYAC8vEP0vFzz9PDwQ/RD9L/0XPBD9L/0Q
/QEvPDz9L/0v/S/9L/0Q/S/9EP0uLi4uLi4ALi4uLi4uMTABSWi5ACQAnEloYbBAUlg4ETe5AJz/
wDhZJRQGFRQVFhUUIyIkIyImNTQ3Njc2NzY3PgE1NCMiBwYHNCcmNTQ+ATc2NzYzMhYVFAYHBgcG
BzIzFjMyNjMyFxYDNCYjIgcyFgc2EyIGIyIjJiMiIyYjIjU0NzY3Njc2NTQmIyIHBgcGFRYfATYz
MhYVFAcGBwYHFBcWFzMyFzIzMhYzMj8BNgE0JyYnBhUUFhc2EyYnJicGNTAXAkcIAS1G/uxFCTIc
By0TKSM8BRAqIDQ7FyggCAYMJ1RKRFlsLyYSIy4KER8iDhBCEQ0VG+QYCQYRERoDEMUVVhULFhYL
ChISChk5QAYpHBZdTjc8GTE6DyELfykgLYQbJR4eCAwCDBUnJxUggCAmIwUB/kcREAcKIgYKEgMF
BgsVJfsMMgsHDg0HZwSHEh8iCCoWKhc3BigIFBQWBAE3LQUBIiENLBsYclopYjMXGyUKAQgGCAES
CRESHBAW/ukFAQEPBy81Bi9INw9PYg8GGBsOHDgEOi8gPmIUJR8eHCw7DAEGAUYVAVkGIB0JIAYE
NggU/kYJEiZLLwFuAAQAEAAFAe0DEwA/AEgAewCFAJlARgGGhkCHPIB8b1taQ0AnfnFkWFdNQjot
HQlRAjZ4AjwTAmIjAmpiRwI2hAI8ZmcFbQ0FAHMFACUFXhAFbVUELy8BAAABLUZ2LzcYAD8/EP0v
/S/9EP0Q/RD9PAEv/S/9Lzz9EP0Q/RD9Li4uLi4uLi4uLi4ALi4uLi4uLi4xMAFJaLkALQCGSWhh
sEBSWDgRN7kAhv/AOFk3IicmJyYnLgEnNjc2MzIWMzI2NTQnJicmJyYnJjU0NzY3NjU0IyIHJicm
JyYnNjMyFhcWFxYVFAcGBxYVFAcGEwYHFzY3NjU0ByYnJjU0NzY1NCcmIyIHFTQXMzI2MzIXFhUU
BxYXNzYWFRQGIzInBgcWMzI3PgE1NCcmFwYHFjMyNzY1NLAiCBMOBg8JEQEREB0NCywLEyE0FggD
CwEGBBMcHCYqHk4LGhkEBQ9WaTJ2IhYSFRkXI2prUnoEVBIZHhxlERAVEl1DN0NbQg0EEEAQMiIu
dgUKEyA0OyUBQA8dLhxeNyhMGRxTBjcEFBENCwUBBRIIFQwZDSMkOA4RDx8DKxwNPgUTDgoHCQwL
FBIYIAMlIg0SWSsrIRUeIxkrMCwfV4N1NigCeW1JBQE9Nx8RvwECBA8CElhOPCMcGggCRA8RFS9Q
JCRJAQEvISQ6DB09FBgRcCsqKi+iI04ZKSIWEgAAAAAFABYAEwIqAwsAQABJAHsAigCUAJdAQwGV
lUCWAJCLhXx6cV9TUUhBNC4DkIuFfG9jW0pGLSsYFQBXAj1pAhxBAjlNTAM9UAM5DQQPKgQmdgUF
JgEQDwABHEZ2LzcYAD88Py/9EP0Q/QEv/S/9PBD9L/0Q/S4uLi4uLi4uLi4uLi4uAC4uLi4uLi4u
Li4uLi4uMTABSWi5ABwAlUloYbBAUlg4ETe5AJX/wDhZARQGByYjIgcGBwYHBgcGByMGJy4BNz4B
NyYnJjU0NzY3Njc2NzY3MhcWHwEGBxc2NzY3NjEyFhcWFRQHBgcWFxYnBgcOARUWFzYXJic1NDY3
JwYjIiYiNTQ3NjcmJyYjBgcGBxYXFhcWFRQHBgcGBxYzNjc+ATMyFxYzNgEOAQcGMQYHBgc2NzY3
NhMGBw4BBz4BNzYCKjAMCjAFBgYMAgIEIAcQFBg4PxQBBDIDODdWEhsCCQkPCxcvERoVFgMQHkAH
FgMhHgpoAwYOEgIXFyK/CxAFEwcKDrgYMRwBXCcQAVYyEhYEBRgRCw0bESAgUUkmDA0PAgkgWhkF
HwMHEA4WHwQL/o8TDQMFChINFAgMByMhmhcgCS4BDh4IGAG2HG4CBC8qRB0dGRYHDQEJChIPJdIV
CwwVGSQzTQgoJz0IESIIBgYMQYIMKEAGDg0RAwYKHy8+DgsKEcEDDAhMCgIGJ4MLGQUebRkMnB4P
I0JPFwEFBDBfMWIKDgwPBQwHLDMGQH8MNcYQIwUIHAFLDxgUIBw3LEwECgh8df61CxYN2RcFCwpx
AAUAGAANAlEDAAA7AEkAfACIAJgAl0BEAZmZQJoAkIuHg4F7X09EPCkfBJCJgXRhU0o8GwgALAJX
RCQCV2kCDn0DV3gFBgYER5UEFIUEJiIEW2UEjjIBFAABG0Z2LzcYAD8/L/0v/S/9EP0v/RD9AS/9
L/0Q/TwQ/S4uLi4uLi4uLi4uAC4uLi4uLi4uLi4uLi4xMAFJaLkAGwCZSWhhsEBSWDgRN7kAmf/A
OFkBFA4BByYnBgcWFxYXFhUUBgcOASMiJyYnLgE1NDc2NzIWMzI1NCMiBiMiJjU0Njc2NxMWFxYX
FhcWFxYHNCcmJyYnJiceATMyFjcmJy4BJwYHBhUWFxYVFAcGIyInJicGBxYXFjMyNzY1NCY1Jicm
JyYnJjU0PgEzMhYzNgM0JyYnFhc2MzIXNhcmIyIGIyInHgEXFjMyNzYCUR8OEEOPBwMZMTwnIicw
HGoiJ0ZOFgkWEREGB30jOmAKJAkNMggBAwlUN2wWohYeBAUFRQkHLB4dJk0KFhYPhUI2NT5hYwUq
JmUuVSQgJSItJyYQC1EIHENkQUoRGiQcOhkaKB0GCSuvLAnaTRNlARE8BFQcA1oGBgNoIV1vBRZP
Rh4jM0ACUg5oDQQeIBcbBQwPRj5DPEskFSMPEhQIPw8HMC0LLB00B1cPBBkDFy8BDwIKAygEDQUs
J3gUGwcHBAQMGBEfOcMPDxAKCDd7b0YBDxpMIhcUDAwMEzAmAwgtNGAPJwgrEg0GAgIECQiPCjgm
/rA2FAULBSQKSgihEikvHRoPDg8TAAAHABgAFwIUAw4AJgAwAE4AWQBoAHQAfwCtQFEBgIBAgSV6
dXRvbmxaVEAzLX5vblhUNS8tLB4TAj1LAiV4Al1GAgp0aT0CZSgCZXIFBGEFTygnBRBWBAQYGgQv
MR4EIE8ESEgEUhABBAABCkZ2LzcYAD8/L/0Q/S/9PC/9PBD9EP08EP0Q/QEv/RD9PDwv/S/9L/0Q
/S4uLi4uLi4uLi4ALi4uLi4uLi4uLi4xMAFJaLkACgCASWhhsEBSWDgRN7kAgP/AOFklBgcGIyIn
JicmNTQ3Njc2MzIWFRQHDgEjJiMiBwYHNjMyFx4BFRQDIyIHBh0BNjcmByIHJjU0NzY3Njc2NTQv
AQYHBgcGFRQzMjY1NCcmAyIGIyInFjMyNyYnIiY1NDc2MzIXFhUUBwY3NCYjIgcxMjYzMhcHIgYH
FjMyNzY1NAHqHDY5LFdJRCMUKSFYXGkWIwgDCQcKApEhBgdPLTohK0CRDhUmKT87BjdWZRUQFRxM
bQIEBxUSsUEh8EVmGRxICB0HRTVBRAw2FG8jQz4zOSoeITotQyIUMBUHHQc0HFIoOQUXFikoNYEn
ICM6NlQxVTWCZ0ZJMhdaEAcDAnETJR0KDFwubQHMERIQAx8BDtRMAiMUN04gWQ4hAhAYAwcDHtJp
LvdsRlAeIf6nBREpEgtOPSM0IRsVGCpBIBiJExcbBRcEKyUWDRAdLAAABQAMABICMQLsACwAOQBE
AGsAcgCTQDwBc3NAdABvbGZbVlVLSUE6Ni8ZFW9tbGReUz46NjEvHxURZmgIBgQEBmZoCAcGBgdF
AgBNBCUlCwABH0Z2LzcYAD8vEP0BL/2HLg7EDvwOxIcuDsQO/A7EAS4uLi4uLi4uLi4uLi4uAC4u
Li4uLi4uLi4uLi4uMTABSWi5AB8Ac0loYbBAUlg4ETe5AHP/wDhZARQHBgcGDwEGBwYHJicmJyY1
NDc2NyIHBgcmJy4CNTQ3Njc2MzIXHgIXFicWNzYnJjU0JicWFxYHBgcGBx4BMzI3Njc0JyYnJgcG
IyIHBgcGBxYHMzI3PgEzMhYVFAcGBwYHFhc2NzY3NgE1NCcUFxYCMSAaGjQlVA0cBRMFSzQGBFJL
GSU6QBkgCB0FCQYKvK4uOA4GIggDBB8KAgICAwwMAgYB0zFNcg0FIAUJuAbMBwYGDRYZCiMXDZRh
Pw0BCC+wBiIHBxAfHAkpZRs9QH8YGCb+7WgBJQJWHzcoKVhFnxw2CAcDJRoJKBIOn5IqDA0CGgYa
D34NCgUIDw0GAyUNKSUGCgQDDxEEFxoIECYQQQoHCwIGGR8DShUeGhkBAQICAQkGCkguGQEKDgYH
PjoQRdETKHHlLCxF/dAJDzwIERIACgADAAwCFAMWABkAIQAsAFAAYABvAHsAiACUAKMAACUGIyIn
JjU0NyY1NDYzMhcWFxYVFAcWFRQGAxYVFAc2NTQDHgEVFAcWNTQnJgcmJyY3PgE1NCYjIgcGFRQX
FhUUBwYHBhUUFxYzMjc2NzY1NCciJyY1NDc2MzIXFhUUBwYDIicmNTQ3NjMyFxYVFAYDIgYVFBYz
Mjc2NTQnDgEVFBc1NCY1NDcmEyIGFRQWMzI2NTQmJyIHBhUUFyY1NDc2NzQmAaBFSiU2szElemkK
TmEqMztHSCg1HS5GGygEFBYaGQo4AgogKIpaTTEuJAcKDwEdOjxrOTA4FRnONisuGyA2OyEfFxsd
RisxFhwudyQUQi4gKRojHhMPjw4WHwUzCEgjMSInHjIdgBsPCyUJFBIYGCoeEjnKbzErSWl4HCMt
N2FsJkdiMGoCdUlMKUEQUHH+8RxeJx0NAS8rMjo2ED8JBhVLJ1mBPDhPPSoJBQkJDQInV2tCRRYZ
LjIfLJwlJjU4Jy0pJTwuJi7+xh8kRDIrNFowHytEAe4yIiQeIx0kMiwNPRYhHwEGFgY7JxX+qDYk
Jx4zHiklNCcdIzwZGBkbIB0QDRYABgAMAAsB7QMKADMAVwB2AIwAlgCkALZAVQGlpUCmAKCVf3Bv
RDajoJ6XkY2Fd3NyaVhKSEA+PCACABoDbx4Db2UDJzQDBEYDDU0DCgdUUlADBEQDDZkFK46NBYty
BQ8hIAVnYQQrKwEQDwABJ0Z2LzcYAD88PxD9L/08EP0v/TwQ/QEv/S/9PDwvPP0Q/RD9L/0v/RD9
Li4uLi4uLi4uLi4uLi4uLi4uLi4ALi4uLi4uLjEwAUlouQAnAKVJaGGwQFJYOBE3uQCl/8A4WQEU
FQYVFAYVHAEVFAYVFAcjIicmJyYnJicmNTQ3Njc2NSMiJyYnJjU0NzYzMhYXFhcWFxYHMCcGFRQH
BgcGFxYHFBcWFzY1NDc0NTQ2NTQ2NTQnJjc2NzYvASYnJiMyJyYjIgcGFRQzMhUUBwYHBgczFhc1
NDc2BxQHBhUGBwYjMCcmJyY1NDc2NzYzMgcjIgYVFBcWFzYnJiMiBw4BFRQXNCY1NAHtAQcGDj0N
IycGCgsLCwwDAwEKGx01Pi4sGDJ9QksnKRAGCxwVGBIDBAEBAwIHCA4KAgEGBwIBAQEDAzIGCBsW
Dg1AGTptLRbnIgMEAQMGCyNGCQ1iBQYBAQMMMCkqMREQLxFDLB0tESYhMQgBTw0LBwgEGSQDAnUb
MzIaEVMQF0sXDTwNdxYEBQMFEAwLDwwOFhoJvwoOEj87Oh44cgsFCBQLFjYNNH9/EyAmDRxdSy0F
CA0OQRsPIiIQGlkbDkYOCyceFAcUEWQFAgYFCQRkMhqMGRIcJQhLlAUFzFSDxScVIC0JFBQdDgoK
ESUXKycJBEMvEyAEBgUXZRMFA0EIExADCQM3AAAABgAAABUCqAMNAD8AYgBzAIAAjACTAJRAPwGU
lECVAJKQi4V3ZV9bT05BD5KNh4F7dG5jU0AASkhMBiclJScTAiERAldWTAIhLwQzcAUKfQUbMwEb
AAEhRnYvNxgAPz8Q/S/9EP0BL/0vPP0Q/YcuDsQO/A7EDsQBLi4uLi4uLi4uLi4ALi4uLi4uLi4u
Li4uMTABSWi5ACEAlEloYbBAUlg4ETe5AJT/wDhZJRQHBgcGBwYHBiMiJicmJwYHFhUUBwYHBgcG
IyInJicmNTQ3Njc2EzY3Njc2NzY3Njc2MzIWFxYXFhcWFxYXFicDDgEHBgcGBwYHBhUUFzMyNzY3
NCYxNTQ3NjMyFxYXNjc2FyYjIgcGBwYHDgEHFjMyNzYFLgEjIgcGBxYzMjc2ExQHBiMiNTQ3NhcW
By4BJwYVNgKoEBozHDYGGRQEE0YBCBkYJBMHCyQCCUsWCzAmAhkUDQ0DSw0XBw0ZHxYXDiYgBAo2
BA8dFh4jEhscJ27OHIQdEgcNCgYvJwQMFj4yFAU9NwwVEw4NF0A3VhkCBSEqDBkrChQDJwsEQE/+
mQcUBAQ0Gy8qBAYsMWAKRw0VGSAeDyADEAMGCd4OCAgUEBoCDQpSDUVVBQ2COCAHDRgFCCghGwIV
EydBKCgLATg1LAQHDQUCAwMJCBsFJj8qSFIlNjZNQAHEDRUPNyZGJxu1kg0HBB8aDg48cA4bGU9C
QgoTEC8iDxIFBQsECQknHydiBRQaDQwjFhgBuxMEHhk4LBEBD0UGGQYhDgMAAAAACQAeAAUCMQMJ
AC0AUQBhAHMAgwCSAJwAqACxAAABFAcGBxYXFhUUIyInJicmNTQ3Njc2NzY3Njc2NzY3Njc2MzIX
FhcWFxYXFhcWBzQnJicmJyYjBgcGBwYHBhUWMzI2Nz4BNTQnJicmNTQ3Njc2AyYnJicmJxUUFhcW
FxYzMhMUBiMiLgE1NDY3NjMyFxYXFgMUBiMiJjU0Nz4BMzIXHgE3NCcmJw4BBzIWMzI3PgEnNCcG
BzIXNjc2ETQmKwEGFRQXFjMyJzQmJwYVFBc2AjEeITEXBQHCsDEGDAsjFRQCAwkRAQ0JFgICBAkC
EidkFRYeGgcbHwcgNhMWIUN/DRYpHAoZGwgCo1sMDwMlPwQNQAcmLxgnyA8qMxk/LQsDGUI0PQ2W
QzQMWA4qCAsPMVESCAFgOxsUWxgCDwcFBjVVPBwYHAUYBQUVAxQRCSdyEQ0WDwoEDAsfEg0QExAJ
IlEKARQPEAHcNjg+DR4iCCqsUQoyLwcMjlNSDRggQggYFSkHBgsEARwGBgoQBSQoFFwEKjQ+EiMY
AViNMl5lJQchcAYBA0sqCg82HgQLBxMYGir+Xw8LDg4kHggFJAQmEg8B/zY3FgwLDZkLEDYMKQX+
tB8zOA8KcwkVBQRW5xgRDwIQQhADAwIbUgQrLWQDESwl/okOIzEDCQgGagQcBEcRBQ1KAAAAAAUA
FwBnAikC9wArADUAPABJAG0AgEA3AW5uQG8ATEY/OjYzLydZSkY9Ozo2AGICCCwCEx4CSEICU1cC
MWoFAiEgBU5aWQUPAhEPAQEIRnYvNxgAPzwvEP08L/08EP0BL/0v/S/9L/0v/S4uLi4uLi4uAC4u
Li4uLi4uMTABSWi5AAgAbkloYbBAUlg4ETe5AG7/wDhZJQYjIicmJyY1NDc+ATc2MzIzFhUUBw4C
BwYHDgEVFBczMjc2NzYzMhYXFgM0JicGBxYXNDYTJicmJxUUAyYjIgYVFBcWFyY1NBMmJwYjIiYn
JjU0NzY3NjcjIgcGBwYHBhUUFxYXFhcWMzI3NgIpR1m5hhQRDgsRgUZhQA0JSAQGEBVCLBwOGh8G
KSsHFRIKC0cDBksLBQEGCwcFLgIDAhyRGhsoMREKIQzaBgc1dxxKCAdZQGQCByJmOFEqCQ8aDxAQ
J0pCQwwrJ4cgjxZGPic5L0d+CAsrEiAuPwUGFg0XCy8RQR0FAQUETQwcAdIGDAYkRwYJEUH+GRkZ
FBsQQgFVDj8pJBwRIhsrVP7hI0USTh4aGlUuIggkRxIZRQsWMVghPEIULhsYDQwAAAAABgALAA0C
QQMTABkAMwBDAFoAYwBvAHxAMwFwcEBxAGtnYFtWSjwga2BOPDQoCiQmBhAODhAaAgBkAkRcWwJE
QgQGKgQ4EgEGAAEKRnYvNxgAPz8v/RD9AS/9PBD9L/2HLg7EDvwOxAEuLi4uLi4uAC4uLi4uLi4u
MTABSWi5AAoAcEloYbBAUlg4ETe5AHD/wDhZAQYHBgcGJyYnJjU0NzY3Njc2MzIXFhcWFxYnNCcm
JyYjBgcGBwYHBgcWMzI3Njc2NzY3NgMmJyYnJicmJxQXFhcWMzITFAcGBwYjIicmNTQ3Njc2NzYz
MhYXFgc1NCcmJxYXFhc0JicGBwYHNjc+AQI+BiQ3Lj96mxw0IxUWERUYGFFRtCEJCQkyMixiSksD
DA0DChcWOWNmLicOPzYYDBMMtxERECNGID4qEQsNI0ttiAkBBjiSHRgiSgcODAEMDwxxFhcjJg1C
DRE+DS4jEhIYExYqIz0BYV9CYyEvAwIzXQYRf1BQRHaBIk6WKCgxMGdCOy0jFSAoDThuYdc3DwUg
HDIaUTf+owoLCAIEBAkXAiAUCBQBeggpDRh+BwsVBtwcODMBJU0nKjUSNSUOLB89IHMmRBE/P1Il
AQkNQQAAAwAHAAoCJQMbADcAaAB9AHJALgF+fkB/AH1xZWRJRkU7OjMxJiVpWFJOQzgvIxwAPwIo
cwMSVVQEGBgBBgABEkZ2LzcYAD8/EP08AS/9L/0uLi4uLi4uLi4uAC4uLi4uLi4uLi4uLi4xMAFJ
aLkAEgB+SWhhsEBSWDgRN7kAfv/AOFklFAcOAQQjIicmJyYnJicmJyY1NDY3NiQzMhcWFRQGBwYH
BgcWFzcWFwYHDgEHBhUwFzYzMhceAScmNQUnLgE1NDc2NyYnIyIGIyInNCY1NDc2NyY1IyIEBxYX
FhcUFxYXFhcWFTMyNzYFNCcmJyYnJicGFRQXFhUWFxYXFhcCJQYHCv6SBxgIBQkdFQ4OAgsJHQ4a
AT8dEwsIEgchSlMdBQWbAw4IBAk3GyoJpkIQDQQUKQj/AAkBGUIqKgQGBxNyBAoCEwgE7gYZBf7l
GwIGDRYUAgYBDwoHJ3iO/q8MEAITExoFDQgLEwUNEQkPug0cIQheCQ4WP5dwcQswJRYTRQcNSzIk
HgkuBBQPEg0iERQkRyUIDgkEBglGLQgDYQgtFDIGDpIBDQwHBxUpGgUBigMJBAJCJSZMCBs1S5gC
XhUoCCkfESQsaRcsNgxsa5BCIQkSKzoEgB9VSSRHAAAAAAYAGwA0AmUDAgAvADoARABLAG0AewCF
QDkBfHxAfQB4cGRjXltKSUc/OzkydW5oY0xJRUI1CnICJDADADw7AxBRAiRXBR4rBFBQBSgeKAEB
JEZ2LzcYAD8vEP0Q/RD9AS/9L/08L/0Q/S4uLi4uLi4uLi4ALi4uLi4uLi4uLi4uLjEwAUlouQAk
AHxJaGGwQFJYOBE3uQB8/8A4WQEWBwYxBiciBxQHFhcWFxYVFAcOAiMGBwYHBiIGIyInJicmNTQS
NjMyFjMgFxYXBxQnFAYVFBcWFzYDNTQmJxYGFRQWJzQnBgczNiUmJyYjAwYWFTIWMzY3NjMyFjMy
NjM2NSMGJyYnNjc2BTYBMCcGBw4BFRQWFzY3NgJkAQcKNbgCSAIoJyUPAQMJQz8BCQ0LDwgQIAk8
Fg8SETUKEwYbBwEbiwoeGw4JBQYBC8MRAQEEDXsQBAUSBwETaWmFUjEBAxFCEAYUAxAJJAkOOQ4D
CRQ1OwcIDi8BAgf+2hcFCQENCwEKFQgCkhMgNAkCBggOBQUKMAQRPBYFBAQkW1IsGgUHBSckEiYC
LRIEIAM7CQEcDz8KBAUIAUX+9jgEFQIIGgYOE58EFh8aIZALCg39uwMOAwJhtQ4EAwcvAQkJCG8D
DAkS/t4cOHINPRADGgNJkjUAAAAABgAeACMCrgLqAD8AUABYAI4AkgCfAKdATQGgoEChAJ6akpCP
V00nJpqTkI9lVVFLQC8zAmlaWQI/ACsCbnl4AiODAhdnEC2VEGtTBTtEBHh2OARhYQQ9Oy0Ea30E
H4cEmB0PARdGdi83GAAvLy/9L/0v/S88/RD9Lzz9EP0Q/RD9AS/9L/08L/0vPP08L/0uLi4uLi4u
Li4uAC4uLi4uLi4uLjEwAUlouQAXAKBJaGGwQFJYOBE3uQCg/8A4WQEUBw4BIyIHBgcGBwYHBiMi
Jy4BJy4BNTQ3Njc2MzIXFhcWFRQPAScGBwYVFDMyNyYnJjU0NjU2MzIWMzIzFhcnJicmIyIHBgcO
ARUUFzY3NhMmIyIHFhc2PwE0JjUGJyYjIgcGBxYzMhUUIyImNTQ3Njc2NzYzMhc1NCcmJyYHBgcG
FRQXFjMyPgE3Njc2ByMWHwEmIyIGIyInFhcWMzICrgMGJwkTDgkKCAcdPStROEEqbhcHDyEmUVxg
Alk6FAEHEQeIOmB0OwsbAQ4CEXoJIQcqKQcruQ8HCxgfQEgIAQ8JMEAY+wwIFS4IEhYPAgYXJCgS
FlYCAQkXEWlHcDQ4VxgYHhMNCwQOJjcsbEhDGEauOEc9AwEGBnsTBQpJDggVVBc3TxM5MCQuAS8Y
LAEEEAwZFBQ/FhEYD2AnDUYRZVNiSVICFyUCGxRPCAIYIDZwdBghAhUUDzoOGQUCLMYVBQcVFxQE
DwUWCS4SBv7NHwcLFQk6LwcXBQEEBQwXNAIZZGFGW0tQEAYFBwIWFCkEAgINIXRtd0wocRhNIxgf
CREHDbcHEBYRCwoAAAAFACcAPAKqAt0APwBQAFoAhACQAIFANgGRkUCSAI+HfHZyYF1ZU0tDOTQS
EIuFenhwaFsyGA5EAgsLAkdAAwAuAlFXAmRqBScnBQEYRnYvNxgALy8Q/QEv/S/9L/0v/RD9Li4u
Li4uLi4uLgAuLi4uLi4uLi4uLi4uLi4xMAFJaLkAGACRSWhhsEBSWDgRN7kAkf/AOFkBFAIHBiMi
JyYnJjU0NjUmJwYHJicuAjU0NzY3Njc2NzY3Nj8BJjMyFxYXHgEVFAcGBxYXNjc+ATMyFjIWFxYH
NCYnAxYGFRQXFhc2NzY3NiUmJwYHBgcWFzYlJicGDwEmIyI1NDc2NyYjIgcGBwYVFiM2NzYzMhcG
BxYzMjY3Njc2NzYFNCcGBwYVFBcWFzYCqlEMFBMSOj8HHBURPxgyE0tOCRcGBwEJFBkHBAUHDgkI
M1UWChwJEAkLASYpBgsKDhkVUSkREBAbEARKAQ8FBwEWEw4PDP7NCRAKCQ0BCxcLAR8qVAkSBFgw
RQ4KCUAYCxIWISNzBgoRFQ59TA4XRg0fCwcFBAMVJP7CIQkTFAkHCDkB6Bn+thsuCAkGTxAUUBMI
CESJAhcYEUgKDBUaCDtedyEaGh4SBAEJBCkMFREQHygHAwcNS0QLCw1TTR8OWQj+jwokBQoSFwU1
V0dIKcUQFhclNgcDBSBHBgc3bgQPEhg8LCsFBUCgpzUfIEBlFEmUChguICAQTYbICicSPUAODhMP
EKwAAAUADQAHAkoDFwA6AGwAdgCDAI0AnEBBAY6OQI8AjIiCe3Zxa1hWUEJANjIWEoqEfHNtaWhU
TkosJhoOCgwOBmhmZmhQUgYgHh4gPDsDAHcCYiIBBgABGkZ2LzcYAD8/AS/9L/08hy4OxA78DsSH
Lg7EDvwOxAEuLi4uLi4uLi4uLi4uLi4ALi4uLi4uLi4uLi4uLi4uLjEwAUlouQAaAI5JaGGwQFJY
OBE3uQCO/8A4WSUUBwYHBgcmJyYnNDc2NyYnJicGBwYjIicmJzY3Njc2NzYzMhcWFRQGBw4BBxYX
FhcWFzY3NjMwFx4BBzU0JyYnBiMiJyYnJicmJzQ3NjcmJwYHBgcWFzYzMhcWFxYXFhcWFRQHBgcG
BxU0FzYDNCcmNQYHFBYXEyYnJicHFhcWFxYXNgcmJyY1BhUUFzYCSiBJc1OWDg0LCiE2PhAMCgoM
QT0DBwoHCAoXCCVovEMEDRANFAUPPw8EDhIEBBIFLCARDggaHAkICFcTEgsGBQgODCFAJygCEjx7
B7IFC0Y6DgYKCAUGAxsUHBcWKjofgPEHCwQFDgHoAhocBRECCAsCBBgLbgEOFQsiBaUKPxUWERkV
KSAgEUcPDD9YTUwBDAo1FiwTIwoFESoPNS8TCkIDBgsGIjVFEiRKAQoIBA1pEQYVHhgZEzsmJhkz
N28PDggHRBQPGgEdGzYSChA0JiUSW0UmFwgEAwgNCARmGQHfDhglAQYMBFcC/tQ6YmwuFRQiKQ0c
owK5DiMxASEDBE4FAAAEAA8AHQJ3AxUAMAA6AEgAcwCnQEsBdHRAdQBcUU9OSkE2MSMhGGBMS0lH
QTYoEwZKSUpLBiwpKSxJSgZKSzc2NjdwAgAyMQMAOwMIaANFHQJVYgUOGwVHWCwBDgABE0Z2LzcY
AD8/Lzz9EP0BL/0v/S/9L/08EP2HLg7ECPwOxIcuDsQO/AjEAS4uLi4uLi4uLi4ALi4uLi4uLi4u
Li4xMAFJaLkAEwB0SWhhsEBSWDgRN7kAdP/AOFkBFAcGBwYHFhUUBwYHBiMiJicmNTQ+AjMwFjMy
NTQnJicGBy4DJzc2JDMyFhcWBzU0JyYnFxYXFgM0JicuAScWFxYVFAc2AycFFRQXMzYzMhcWFRQG
IyInJicGBwYHFjMyNzY3NjU0JyYnJicmNTQ3NgJ3Aw4mHRw9PjJmSi05eh4XPhE7BoAcMBIREhE2
DTkPHwEJDgGMDQg4BAkbAggpBgMJChkxCgcUChMbHBQqDRb+kiMGXwofJB5JPSkuJiYIEgwNOpIl
SUQhKxgUFAEMCzYiAnEICQwNCQnHYl83LBoTPS8jAwhKChhuTjhMQEEBGQMrGHMQDQZLOQoWQxYo
BhInGRkuCv5/HfwQCgoGMomMLxwsMQHSaE0HF1IhnIg3OjshHR0DGBEQcRAOGSE8O2hRUQcoJQIN
DAcAAAAEACUAEwJoAv0AKwBgAGkAdAB/QDYBdXVAdgBsZ2NfXFA/Ox4cBgJwamVFODQmIxIIBlYC
AFkCACwCAGEDAHIEDEMEFhYBDAABEkZ2LzcYAD8/EP0Q/QEv/RD9EP0Q/S4uLi4uLi4uLi4uAC4u
Li4uLi4uLi4uLjEwAUlouQASAHVJaGGwQFJYOBE3uQB1/8A4WSUUByInJicWFRQOASMiJicmAjU0
PgEzIhcWFxYXNjMyFhcWFRQGBxYXFhcWJzQnJiciJyY1NDc2Ny4BJwYHBgcmJyYnBgcWFxYXFhce
ARcWFzY3Njc2NTQmNTQ2MzIWFzYXNCcGBxYXPgEHJiMiBwYHFjMyNgJoVyEkHBsTDZgIDTwIBn8L
hQ4DFRQnER48Dg54BhRACQEjMBEjMjs3DQEQDigRIBgyGRwdLxQRIB8CCXcBIgYPCBMVDAUHCkMH
LRoDKAkECI4JVBYFLB0FCAU8yhoDAzU4DQsMCG+7DUskHh5dGwwHJS0OCgJPFwkMKgMMIjpRoEYN
KBYNuQwMISwWLAYDPzoODgsCEF4qYhAjCkRDawgefnkCAiELkCpUJkVKQB4mFgoCCQwJBRxyHgQL
qQFJKgUOGCsFBAE1ZRUQEAIWHgAABAAtAB4CrQMCACcAMABAAF4AYEAkAV9fQGAAW1BKPzgsKB9T
UkE5ODEtLCgTACEFREMXAQoAARNGdi83GAA/Py88/QEuLi4uLi4uLi4uLgAuLi4uLi4uLjEwAUlo
uQATAF9JaGGwQFJYOBE3uQBf/8A4WSUUBwYHBgcGBwYjIiYnJicmJyY1Njc2MzIXFhcWFxYXNjMy
FxYXHgEnJicmJxUUFxYlJicmJyYvARUUFxYVFhc2BSYnIyIGIyIGIyInJicmJwYjFRQXFhcWFxYX
Njc2Aq00IiJjtQogGg8QQwMQExQMBAJVNyAeQg0WAwMEDo48Ex8cBgQVIQMPBw0NCf7aDQQDAg0Q
JwkPChQMASEIDhwqpygFEgULCAQNChRmKg0RAggZBgckR3V3EAkEBBAXAggHOQ9hrb9PHEoBDwpO
QoMzM0gXJx0bEwp7JSI6BgwMLB0IayM6LzBBhSYHITZRBVWoA14lSSoDQkaNRYsSDSFHYQtu3BIl
Bg4eAAAABgAHABsDFgL5AEEASQB8AIYAkgCgAJFAPwGhoUCiO5uTkYmDfXBsZmBOSC4XEQsHm42D
fXZeSkI7IB4HBgSHAnJGApN4BQBDQgUxTAUxVAQoKAEAAAEeRnYvNxgAPz8Q/S/9EP08EP0BL/0v
/S4uLi4uLi4uLi4uLi4uAC4uLi4uLi4uLi4uLi4uLi4uMTABSWi5AB4AoUloYbBAUlg4ETe5AKH/
wDhZJSInJic2NzUGBwYjIi4BJyYnBgcGBwYjIicuAScmJyY3Njc2NzY3NjMyFxYXFhc+ATMyFxYX
FhcWFxYVFAcGBw4BAyMOARUUFzYFJicGIyInJicmIyIHBgcGBwYHBhcWFzY3Njc2MzIXFhcWFzY3
NjMyFRQHBgcWFzY3EjcHBgcGBwYHNjc2JyYnBgcGFRQXFhc2AwYHBgcGBwYHNjc2NzYCXwlUSxkU
MwUZFQYLWxIEAgILGQUWGRMGMzgZERQGBQULCw4QAQw+bLMMBgUGAQ8gIgpJWAYUFBsGAyosGQY5
WhQKHQMhAQJEh0sVDQ8QCGQdGEINCAYGAxQPARRaFBQiCgQGDhgPEBImIiE4CRIaGBhJNgsEOx7X
CxQFGRcHFBgdowsWAQkFCAkCCr0kDAMHECECBQ4dBw0PGygkDl57BQMfHBkNFBAQP38UGRsREwUK
CwoJJmRkcVYTIlUXCxQcBSEZHSECBgYJDAcVP8zRLgowAqAKNAwGCTUwFzSFR1ALDwcyRj09GWtR
NAYgZWWmCwNcOjoFBzY2WSBKZlZWFxQZFgEKou4FDgZSSRoMClhcLlsBIhUPEBoiCQcBbRsVBi9W
4x84BQonTXsAAAAFAAgADQJ+AwgAPQBDAHsAgwCWAKVARwGXl0CYAJWLg35yZlpUSUA+KiaNhH9+
fGpdXE1CPiEAYmQJHx0dH5GTBh8dHR9wAlJRRUQCOwwGBXh4BQkQBRY1ARkAASFGdi83GAA/Py/9
L/0Q/TwBL/08Lzz9hy4OxA78DsSHLg7EDvwOxAEuLi4uLi4uLi4uLi4uAC4uLi4uLi4uLi4uLi4x
MAFJaLkAIQCXSWhhsEBSWDgRN7kAl//AOFklFAcGBwYjIiYjIgYjIicmJwYHBgcGIyIGIyInJicm
JyY1NDY3NjMyFxYXNjc2NzY3NjMyNjMyFxYXFhcUFicmJwYVFBM1NCcmJwYHBgcWFxYHFQYjIicm
JyYnBgcVFBceARcWFxYzMjYyNyYnJicmNTQzMhcWFxYzMjc2BzQnFRQXFhcnNCYnJicmJwYHFhcW
FxYXFhc2An4DER4XMAw7EgklCBQPDAsCBREXDzkQPw8VDAUFCREaPAdoRAwcERESBw8UDTUvGgQQ
BBQWDwwJCgbbHBAZ+xsFIBQrIiICGhcCCAYRHRERSC1lNQcJAxMKFgUFDTgbFAUKAhoRDw1HKikJ
BSE5Pb5nIRsb7A8BCQ8EFAoYAwwQAgYPCQwXpAkMPxcSAwUfFxgJETALCAk/KSpHjsMiCFMCHCsc
HC0NHhUNDAsIhFSNcXEEE9OOlB4VN/54BzDbL/4KBwUGOJmMRA0HQSorrlUTAwcOHSQOz1KkAgkI
HjsGZEEpFIxUVAIODi0JvwgxTDw7Fg03DEGDYrEVIiNKYQxBgSVMHAAGAAwALwISAw0AHgAvAEwA
WwBtAHcAc0AxAXh4QHkAdW44cm44MFwCTT4DDw4fAgAnAjRjYgJVSiwFCGAFVyMEGWcFUQgZAQEO
RnYvNxgAPy8v/RD9L/0Q/TwBL/08L/0v/S88/S/9Li4uLgAuLi4xMAFJaLkADgB4SWhhsEBSWDgR
N7kAeP/AOFkBFAcGBwYHBiMiJyYnJj0BFDc2NzY3Njc2MzIXFhcWBzQnJiMiBwYVFBceATMyNzYF
JicmNTQ3NjcGBwYHBgcGFxYXFhcWFxYXFjMyNhMUBwYjIicmNTQzMhceAQc0JyYjIgcVFBcWMzI3
NjU0NhcmBwYHIhYzPgECEiQtSxcYFBtjQiQiIQ8EEhI6MRJGGU4+MB8YHzJDbmkwH38QQxRTNC7+
1kUnJAQDEwgMCQkJAQENCwsECwoKEAoEFQQl2BQZL0YcDzwgDCY/QhUbJRAJEhYVEBAPAioKFBkD
AREPCBQBdklSZiINDQozG1xWNV4ETx0/KzUsBBRYRW5YRWR+qXxSaqpnDRpQRYwwWFBWOhoWQAUX
JCMoJDI7KysPFhITHwUDCgEXMSIraDtMhAwjkzIeNUUOTxM+SiAcFQIKKAIVGgEEBiQAAAAHABIA
EwIWAwYAJAAwAEwAVQBlAHQAfgCNQD8Bf39AgAB9eG1mWk87LSZrUU1EOSslG2ACVgoCPj0HAkF6
Al1bZnUDVjECAFMEEzcEIWkEZHYEcyEBEwABG0Z2LzcYAD8/L/0v/RD9EP0BL/0v/TwvPP0v/S88
/RD9Li4uLi4uLi4ALi4uLi4uLi4uMTABSWi5ABsAf0loYbBAUlg4ETe5AH//wDhZARQGBwYHBhUU
FhUUBwYmBwYHBiMiJyYnJgMmNTQ3Njc2MzIXFgcnBwYHBgcWFzY3Njc0JyYnJiMiBxATNjc1NCY1
NCY1NDc2NzY3PgEDJiMiBxYxMjYTFAcGByc0NTQmNTQ3NjMyBy4BIyIHFiMyNzY3NjMyFycGJwYV
FBYVNgIWUEEiQgEFEw0yCwYgGA0MFxQHDBEQBQxSQSiVTFc3FwwrNB5KFwg4NzsyMilDMg2fSSxC
RAYKHxUVLzIvSvMZAg51IQ1UjjozOQwMJAcvZBoGJxMQKCMBBQgGFBEJCwwRFCkDBE0B80ZyFAwW
AwQcchwmBQQBAgEJBx0ZEBwBDPVTFAcPCwg6Q/4CAiETChAXDxQTF+k/LCYSDRj+9P6jDAYHFlgW
CiYJEAUCAggUE37+NiYRJxMB/TUkHgILAR4WWRYUBAE8EBYJIwUBAgIlDAECCA8KJQoeAAcAAQAW
AhsDAwAiAD8AQwBOAG0AeQCRALhAVgGSkkCTIXZTT01GQ0E8OgmRjYt6eHJYTUNBPiUhHUtNCUFB
QkBAQVUOg3QCYmoCYhECMjICEyoCG0aDAmJwBWZ+BWZJBA0uBBc2BESJBFwXAQMAARFGdi83GAA/
Py/9L/0Q/S/9L/0Q/QEv/Twv/S/9EP0Q/RD9EP2HLgjEDvwOxAEuLi4uLi4uLi4uLi4uLgAuLi4u
Li4uLi4uMTABSWi5ABEAkkloYbBAUlg4ETe5AJL/wDhZJQ4BIyInJicmJwYHBiMiJyY1NDc2NzYz
MhcWFRQHFhcWFRQnJjU0Njc2NTQnJiMiBwYVFBcWMzI3NjMyFzY3Jg8BPwEFIiceATMyNzY3Bjci
JyYnBhUUFhUUBwYjIicmJyY1NDc2MzIXFhUUBwYDJiMiBxYVFBc2NTQHNCcmIyIHDgEVFBcWFxYz
MjcmNTQ3NhcCCwVJDQUWDg8IBBk+MC0aH34DBTpFZ3NFORAGDjdpAg8BAzM+ZCYkeRMahjBXEQMM
PRIjFxQDKQT+6CQkCRUXcCgBBEFCCBUJEic7LikVHBEbDgobJUxHIRgFBzQFERQFPQ0DLBcdOB4I
BAoICxQKERQKHyEjG2wOSBUODgcCFQwJDjfgLDlyZnuCbHxuHwYMMRoZaAkBCysKGzZwZHoYUt4k
cZUuCTIXLRV3EyoXMQsUDCQJEirTHw4PGAcCSAMRFBEME1A6N1hAV1Q8UCYmPQEdAwokpw8NJRuh
p0EvPCUfPhktOE0LBgYgERotMQcABwAB//cB8AMXADMAZABqAHMAgwCPAJwAs0BXAZ2dQJ4AmJON
aWVXU1JQEYRxa2dfWUgGJAITfQJ0kAJ0CAJQahcVAxMCUDQCAJYCeoyKApp3BYFNBRyGBYFyBCA8
BCxKBHFwawAsARkAIB4cAw0AASRGdi83GAA/Fzw/Pz8vPP0Q/RD9L/0Q/RD9AS/9PC/9L/0v/Rc8
EP0v/RD9EP0uLi4uLi4uLgAuLi4uLi4uLi4uMTABSWi5ACQAnUloYbBAUlg4ETe5AJ3/wDhZARQH
BgcGFRYVFAcOAQcmJyYnBhUUFRYVFCMiJiMmBwYjIi4BNTQTEjc2NzYzMhcWFxYXFgc0JyYnIicm
IyIHBgcGBwYHBgcGFxYzMhYzMhYzNjczFhcWFzY3JicmJyY1NDc2NzYDNjcmJw8BJicuASsBFzYB
FAYjIiY1NDY1NDc2MzIWByYjBiMGBwYfAT4BJzQmJxQGFRQXNjM0NgHwOw4hHGQJDGIVGB8lDQMB
HQoqCQgOEQUPFSwoKgsFGhUQEyMqC3UxPR8THjkBb1MHDBUHDRAREgcBBQUBBgsEHAMPJBERCAoO
O0YIHDgLGgIqIygwGyiUBQQrPAkjAgUIUwwaFCcBCmQ8ExALJAgyJTUiGA8UAgsBAwMBGC5kFwEE
AwwKAwIxcEQQFhMBoSgiDQ81BRw6RxUKGwoWFwxVCgEBAQtGCiwBLwE2FAoHBggJAg4oMUQVIDMS
FhAHKVNycoNhCiAbDwMEBpCRDnOKDRAjHjsFQzgLAikxJzr+CQMEXXEJ7AkPAwsdAQI9O1ILExtu
HBkGATAxEgEDDhgyDwQ6HAQnAw88EBogAhBFAAAABAARADIB6gMQADoARABvAH0AhkA7AX5+QH8A
dmZRQTsuEHZpaFJDPDsOKw5gMwJNRQIAcBYCYFoCIDEFT1YFJXwEBhMEZGsEcnQGJQEBDkZ2LzcY
AD8vLzz9L/0Q/RD9L/0BL/0v/Twv/S/9EP0uLi4uLi4uLgAuLi4uLi4uMTABSWi5AA4AfkloYbBA
Ulg4ETe5AH7/wDhZARQHBgcGIyInJicmJyY1NDcyFjMyNjU0JyYnJicmJyY1NDc+ATMyFxYXFhUU
BiMiJiMiFRQXHgEXHgEDNTQmJyYjIgcWEzQnJicmJyY1NDMyFzc0JyYjIgcGFRQXFhcWFRQHBiMi
JwYHFRYzMjc+AQcmJxYjIicWFxYXFjMyAeoJBwgozhw4RQcFChw9DHo0DSASDg47OjMgHg8Qpi4s
NDwTDysSAWAdEDAjRBYLK2kCAR0HFhknYCQTOkcULF4uMxw6NBQnXk9JRERJHRkiQGUOH1NdPSA0
QnsaETFdVFgQDBYxLRlOAQ0TGhUWgwcICQ0YOwYlcE0fDQ4HBAUcHSBEPyceJChhFBYhGkMSNyQM
Fh4TJSMRaAEUBwMNAg8PAf7OTy4YHSMPIi0/FjkNExI3L0VOLCAfKEIhExFGIkgGKQcKWpQMAQIk
HhcBBgYAAAAABAAHAAkClwMAADoAaABzAIAAlkA/AYGBQIIAe3VuamdiVwwIe3V0bmppYF1VSkkf
Hnd5Bh8eHh95ewYfHh4fUAImPDsCAEVEBDEaBBgvARgAASZGdi83GAA/PxD9L/08AS/9PC/9hy4O
xA78DsSHLg7EDvwOxAEuLi4uLi4uLi4uLi4uAC4uLi4uLi4uLjEwAUlouQAmAIFJaGGwQFJYOBE3
uQCB/8A4WQEUBwYHDgIjIicmJwYHBgcGBwYHBgcGIyInJicmNxMuAScmJyY1NDc2NzY3PgEzMhcW
FxYXFhcWFxYHNSYnJicmJyYrAQYHBh0BFhcWFxYVFAYVBgcWFzY3Njc2JzQmNTYzMhYzMhc2JTUG
BwYHNjc2NzYXNQYHBgcGBzY3Njc2ApcRCAsDCCgIISk2BQYPBQ4KCwYUBhoeDBMrHR0jAkkNJxIh
ITMICQMFDwI0BT4nDUxZIy5hIDoKHSA4HR07flkxNQMKCi1oEA8VCxA1KEwZJAYMAwEDARECHAUu
axj92g8ECA8KCwcIB6gEGwEaDx8PEhISJAKHKUgRGA4QHAwRAT1yISkhIBs1ChkbFA4ODhUBmRMP
BgkJDxEDFRoMHTkGFwMBExcHCBUFDwMoFwMMCgUKHhYOJiEDEQImAwQFDQIpB6HjDhlHiSOEIg4B
EgMNCRVNfQoFBTI2BQoSIx+9CAIOBopfrQoSOWvSAAACABMAPgK7AvgALQBYAFhAIQFZWUBaAEVC
QDAoPi4cACICOEkCESQFNlEFCgoVAQERRnYvNxgAPy8Q/S/9AS/9L/0uLi4uAC4uLi4uMTABSWi5
ABEAWUloYbBAUlg4ETe5AFn/wDhZARQHBgcGBwYHBiMiJicmJyY1NDc2NxYXFhceARUUBwYHBhUW
MzI3NjcWFxYXFicmJwYHBgcGIyI1NDc2NzY3JicWIyImIyIHBhUUFxYXFhcWMzI3Njc2NzYCuy4M
DA8SSG8sL1KSLQwKCCMlKTY1TgwFIRwdAwkBIiI2Hh5AfQoKCUcpURYoFhclP1oQEAwNExYeIFYF
EAUXKyEaCxkbNDAqb1JLFgMeFQH/MnwhICQZZCQNR0ISMSwcU4mUNgQECBQHSAQDWmANKB43pmdo
CRsSNDBfBQtDh04jOnogTEgjH0AJAQEIqH9zFDUYJhkRD1VNcRBkSQAAAwAMAAMCiQMPADsAVwBn
AHtAMgFoaEBpAGViWFJGPjcvX1lYTjwoGgBOTwYWFRUWKwJITgUcUE8EX14iHwEcAQwAARpGdi83
GAA/Pz88Lzz9PBD9AS/9hy4OxA78DsQBLi4uLi4uLi4ALi4uLi4uLi4xMAFJaLkAGgBoSWhhsEBS
WDgRN7kAaP/AOFkBFAcGBwYVBgcGBwYjIicmJy4BJyYnAyYnJjU0MzIWMzI2MzIXFhcWMRQGFRQX
Fhc2NzY3Njc2MzIWFxYnJicGBwYHBgcGIyInJicmJyYHEzM2FzY3Njc2ATU0JjcmKwEeATM6ATMy
FgKJAgIqNSpbGxorFhVARQkEJAUDBTIGBwgTCicKCy4MIhQMFxIEBgYFNxosHQgVBQgNkwQKJxFy
DSQfHyAgNggMAQcQBgt/FEkIN205ahUrIP8ACgFbFy4LGB4GHwYMJQI8AgcKQlIBUJwvL0cHCQYC
PxMJLAGXLzA4JxgLAg8KIx0HGwcvSDw7UytHOxcpBUEIFgsKKio6MC83N1sKYbotWhIB/ZUBElGm
KlI3/gcHBx4JDxYqBAAEABUAUgL4AvsAPwBzAHwAhgCHQDgBh4dAiAB2bGVhV1BIQjUrgX15dFta
QB4AW10GHhwcHnsECoQEFE0EL1YEIYEOBHl4Cjo5AQEeRnYvNxgAPzwvLzz9PC/9L/0v/RD9AYcu
DsQO/A7EAS4uLi4uLi4uLgAuLi4uLi4uLi4uMTABSWi5AB4Ah0loYbBAUlg4ETe5AIf/wDhZARQH
BgcGBwYHBiMiJyYnBgcGIgYjIicmJyYnJicmJz4BMzIfAR4BFxYXFhc2NzYzMhcWFxYXNjc2NzMy
FhceAScmJwYHBgcGIyImJyYjIgYjIicmJyYvASYGJxUWFxYXFhc2NzYzMhcWFzYWMzI3Njc2NzYD
JicGByMWMzInJicmJx4BMzI2AvgXEREBEw8LCXwrEgEgEA8UJ08UGiMgCg0NEAYXLgtyEQMkBg41
CAwNEAYHBwYYJisKDQ8FDRkeCgQLgQQHHUMiQxUVHxMKBQwoBR0bAz4UERMLChwbDBZCFhQsDiY3
bBAQGQoLFwwNDC0JPwoUFxAQCT8HCjBQBA8bAq0FCQl+DBkYDjsCRClZQUIBclQVERUBPRYWHAIl
IR0mTVwaYcMHGQIBAyMNEWFuFBEQCRIFDxQEQW+IFjwGC11bESFiYo4kFHECCoFkPj5zLQEBFQEH
VrFQngYKIiE1OyQkAQMZNIJhYSf+FwsYDQEcDgsOBAwRHQUAAAUAGQAQAtkC8QAtAFYAXwBnAG8A
iEA6AXBwQHEAbGtoZWBeWU87NjIoJGxpaGZlV1RCPy4YBABhYAIIRAIWUQIIWlkCHEsFDkYFESAL
AAEWRnYvNxgAPy8v/S/9AS/9PC/9L/0Q/TwuLi4uLi4uLi4uLi4uAC4uLi4uLi4uLi4uLi4xMAFJ
aLkAFgBwSWhhsEBSWDgRN7kAcP/AOFkBFAcGBxYXFhUUBiMiJiMiBiMiJicmNTQ3JicmNTQ+ATMi
FxYXMDc2MzIXFhcWJzQnJicGBwYjIiYnJicGBwYVFBYVFAcWFzY3PgEzMhcWFzY1NCY1NDYFJicV
FB4BMzIBNTQnJicVFgU1JjEjFBcWAtlDLi4nJhp9FQySAQ7ACg1YBBZ8HR4fDpQLAQ1UNHZgDhEt
KgcKMCAdDRJpZAYKFDUkIg8yOIGdLiMwYAI4AgZNLi9QfLz+Fi0wC0AEBgFIOCYmK/7VNwEQCQHm
FjciIy8vLEsTXJhwWhBEIxVlJiYuKjoadgFiX15NNjMWHA4KKCUMC11YHlY7KwssLwQCtQwIhz8l
GzYBJkcrK0oFBLUECqidOkMTEhNQ/qgJFjomJRkvJh5GIBgPAAMAEwAGAngDCgAyAFgAZQCQQD4B
ZmZAZzFiOzczKmRgVT0xITM1BiwqKiw9PwYhHx8hTQIIGANGRgIVQgIbSUcFYF9cA1kuASUBEA0K
AAEhRnYvNxgAPzw8Pz8vFzz9PAEv/S/9EP0v/YcuDsQO/A7Ehy4OxA78DsQBLi4uLi4uAC4uLi4u
MTABSWi5ACEAZkloYbBAUlg4ETe5AGb/wDhZAQYHDgEVFAYHBiMiJiMiBiMiJy4BNTQ2NTQ2NTQn
JicmJzY3NjceARcWFzY3NjMyFhcGJwYHBiMiJyYnBgcWFx4BFRQGFQcXMjMyNzY/ATY3Njc+ATU0
JyYDIgYjIiYrARYXNicmAf4VFRsOFAMMMAokBgsuCxsKBB0IDBANDAFxAkdCFEAkEQgSFjdFDB95
AUVPGkJPDgwJIUsEbyBDESMMCAYJaxoBBQoIBAIBGRSeIx+cCiUJCBwHMwcQmAkFAcoXGB4oRBHg
BBUCAwwFUAYbbhsTTRMTGhUUAeQPHh0BIipBHzwkVmpyIG3aKmh7E1erAS1ChBo4HhNIEKcDAwmI
Xy4GARIP2BAIGhb9dQIEDxsCARIABAAGAA8CXAMTADIAOgBDAHEAiEA4AXJyQHMAamlcVko7NzMq
Z2NaVExEQD87NzMqJhUMCwAzNQYmIyMmDAVhEAUmLgQ/Rh8BBQABFUZ2LzcYAD8/Lzz9L/0v/QGH
Lg7EDvwOxAEuLi4uLi4uLi4uLi4uLi4uLgAuLi4uLi4uLi4xMAFJaLkAFQBySWhhsEBSWDgRN7kA
cv/AOFklBwYHBiMiLgEnJicTBgcGIyIuAjU0NzY3Njc2NzYzMhcWFx4BFwYHBgc2NzYzMhceAQMm
JyYnFhcWEyYnJicVFBcWJyYnBgcGByY1NDc2NzY3NjU0JwYHBgcWFzYzMjYzFhUUBwYHFhczNjc2
NzY3NgJcAUmCnCkKNxgVEgTIGT87Ggk1CBYTEBAvuwVJMxwUFxsIAR0BCjIpVAxEPgYINAYSSAwN
BxcFEgJPBAsIGA8JHwUQIV5SKxE2MBAmRgYVIKx9TgsMHwUPsigRbE49AScGKDREFSk7XboJKDdD
HBFAOBkBSgIYFzsZaQsPBgQDDx4BEAsKCw8BnAcTTEOGAxcVJwxYAY5CRgoMNU0E/mUaKhAPCicZ
DwMdOAsaFhMECwVcUBs0aQsIDHQGGRIUMzUHPQcJF7SDXg9qDw4SBw0cKwAAAAAAAAAAAAAAANQB
7gMcBCYFUAZ4B4IIeAlcCpoLwAzEDaYOkA+CEHwRshLKE+wU6BXUFpQX0Bj8GeYa5hwQHU4eRB9Q
IAAg1iHiIsYjoiSSAAAAAAAQAAAALAkHBQAHBwUFBgUFBgUFBQUGBQUFBQYHBgUGBgYHBgUFBQUF
BgcGBwcGBgAACggFAAgIBgYGBQYGBgYGBQcGBgYGBgcHBgcHBwgHBgYGBQUHBwcICAYGAAALCQYA
CQkHBgcGBgcGBgYGCAYGBgcHCAgHBwcICQcGBgYGBggICAkIBwcAAAwKBgAKCgcHCAYHBwcHBwYI
BwcHBwgJCAcICAkKCAcHBwYGCAkICQkICAAADQsHAAsLCAcIBwgIBwgHBwkICAgICAoJCAkJCQsJ
BwcHBwcJCgkKCggIAAAODAcADAwICAkHCAkICAgHCggICAgJCgoJCQkKCwkICAgHBwoKCgsLCQkA
AA8MCAAMDAkICQgJCQgJCAgKCQkJCQoLCwkKCgsMCgkJCAgICgsKDAsKCgAAEA0IAA0NCQkKCAkK
CQkJCAsJCQkJCgwLCgsLCw0LCQkJCAgLDAsNDAoKAAARDgkADg4KCQsJCgoKCgoJDAoKCgoLDAwK
CwsMDgsKCgkJCQwNDA0NCwsAABIPCQAPDwsKCwkKCwoLCgkMCwoLCwwNDQsMDA0PDAoKCgkJDA0M
Dg4MCwAAExAKABAQCwsMCgsMCwsLCg0LCwsLDA4NDAwMDhANCwsLCgoNDg0PDgwMAAAUEQoAEREM
Cw0KDAwLDAsKDgwMDAwNDw4MDQ0OEA0LCwsKCg4PDhAPDQ0AABURCwAREQwMDQsMDQwMDAsPDAwM
DA0PDw0ODg8RDgwMDAsLDhAOEBAODQAAFhILABISDQwOCw0ODA0MCw8NDQ0NDhAQDQ4OEBIPDQwM
CwsPEA8REQ4OAAAXEwwAExMODQ4MDQ4NDQ0MEA0NDg4PERAODw8QEw8NDQ0MDBAREBIRDw8AABgU
DAAUFA4NDwwODw4ODg0RDg4ODg8SEQ8QEBEUEA4ODQ0NERIQExIPDwAAAAEAAAABAAA09NK3Xw88
9QgAA+gAAAAAsgUN2gAAAACyBUkkAAD/XAMoA1YAAAADAAIAAAAAAAAAAQAAA1b/OAAAA0MAAAAN
AygAAQAAAAAAAAAAAAAAAAAAACgB9AA/AAAAAAM9AAADPQAAAlEABgIsACkCdAAhAgYAEAJGABYC
aAAYAjQAGAJIAAwCNAADAgkADAK2AAACSgAeAkYAFwJOAAsCUQAHAoIAGwLfAB4CxAAnAmIADQKR
AA8CkQAlAsoALQMwAAcClgAIAj0ADAI3ABICLgABAgkAAQIJABECsAAHAuQAEwKtAAwDDwAVAvMA
GQKFABMCfAAGAAAAAQAAABoAAQACAAwAAQAAABwAD//ZABwAJv+ZAAAAAQAAACgCJwAdAQMACQAC
AAgAQAAKAAAAlwEwAAMAAwAAAAcAWgADAAEECQAAAd4AAAADAAEECQABABwB3gADAAEECQACAA4B
+gADAAEECQADADICCAADAAEECQAEABwB3gADAAEECQAFACQCOgADAAEECQAGABoCXgBoAHQAdABw
ADoALwAvAG0AZQBtAGIAZQByAHMALgBhAG8AbAAuAGMAbwBtAC8AdgByAG8AbwBtAGYAbwBuAGQA
ZQAvAHQAdABmAC8AIAAtACAAQQBjAHQAaQBvAG4AIABKAGEAYwBrAHMAbwBuACAAQwBvAHAAeQBy
AGkAZwBoAHQAIAAoAEMAKQAgADEAOQA5ADgAIABUAG8AbQAgAE0AdQByAHAAaAB5ACAANwAgAC0A
IABGAHIAZQBlACEAIABCAHUAdAAgAG4AbwB0ACAAdABvACAAYgBlACAAcgBlAHMAbwBsAGQAIAAo
AG8AbgAgAEMARAAgAGYAbwByACAAaQBuAHMAdABhAG4AYwBlACEAKQAgAC0AIABJAG0AaQBnAGgA
dABiAGUAVABNAEAAYQBvAGwALgBjAG8AbQAgAC0AIAAzADMAOQAgAFMAdABpAGwAbAAgAEgAaQBs
AGwAIABSAGQALgAgAC0AIABIAGEAbQBkAGUAbgAgAEMAVAAgADAANgA1ADEAOAAuADEAOAAzADAA
IAAtACAARQBsAGkAbQBpAHQAYQB0AGUAcwAgAE8AZABvAHIAcwAuACAATgBvAHQAIABBACAAQwBv
AHYAZQByAC0AVQBwACEAQQBjAHQAaQBvAG4AIABKAGEAYwBrAHMAbwBuAFIAZQBnAHUAbABhAHIA
RgByAG8AZwA6ACAAIABBAGMAdABpAG8AbgAgAEoAYQBjAGsAcwBvAG4AIAAxAC4AMABGAHIAbwBn
ADoAIAAgADgALwAyADMALwA5ADgAIAAxAC4AMABBAGMAdABpAG8AbgBKAGEAYwBrAHMAbwBuAAAA
AwAAAAAAAP97ABQAAAAAAAAAAAAAAAAAAAAAAAAAAEAfEhIRERAQDw8ODg0NDAwLCwoKCQkICAcH
BgYBAQAAAY24Af+FRWhERWhERWhERWhERWhERWhERWhERWhERWhERWhERWhERWhERWhERWhERWhE
swMCRgArswUERgArsQICRWhEsQQERWhEAA==
BASE64;
            if(!file_exists($font)) {       
                file_put_contents($font, base64_decode($data));
            }
        }
    
        // code
        $characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        $charactersLength = strlen($characters);
        $code = array_map(function() use ($characters, $charactersLength) { 
            return substr($characters, mt_rand() % $charactersLength, 1); 
        }, range(1, $length));

        // image
        $image = imagecreatetruecolor($width, $height);
        imageantialias($image, true);

        // background white
        $white = imagecolorallocate($image, 255, 255, 255);
        imagefill($image, 0, 0, $white);

        // color list from https://gitee.com/ele-admin/EasyCaptcha
        // file https://gitee.com/ele-admin/EasyCaptcha/blob/master/src/main/java/com/wf/captcha/base/Captcha.java
        $colorList = [
            ['r' => 0, 'g' => 135, 'b' => 255],
            ['r' => 51, 'g' => 153, 'b' => 51],
            ['r' => 255, 'g' => 102, 'b' => 102],
            ['r' => 255, 'g' => 153, 'b' => 0],
            ['r' => 153, 'g' => 102, 'b' => 0],
            ['r' => 153, 'g' => 102, 'b' => 153],
            ['r' => 51, 'g' => 153, 'b' => 153],
            ['r' => 102, 'g' => 102, 'b' => 255],
            ['r' => 0, 'g' => 102, 'b' => 204],
            ['r' => 204, 'g' => 51, 'b' => 51],
            ['r' => 0, 'g' => 153, 'b' => 204],
            ['r' => 0, 'g' => 51, 'b' => 102],
        ];
        $colorSize = count($colorList);

        $textBox = imagettfbbox($size, 0, $font, '0');
        $textWidth = abs($textBox[6] - $textBox[2]);
        $textHeight = abs($textBox[5] - $textBox[1]);

        // the x offset
        $x = ($width - $length * $textWidth) / ($length + 1);
        // the y offset
        $y = ($height - $textHeight) / 2 + $textHeight;
        // per char angle
        foreach($code as $index => $char) {
            $angle = mt_rand(0, 30);
            $color = $colorList[mt_rand() % $colorSize];
            $color = imagecolorallocate($image, $color['r'], $color['g'], $color['b']);
            imagettftext($image, $size, $angle, $index * $textWidth + ($index + 1) * $x, $y, $color, $font, $char);
        }
    
        $buffer = fopen('php://memory', 'w+');
        // write to memory stream
        imagepng($image, $buffer);
        imagedestroy($image);
        rewind($buffer);

        // take memory stream data
        $data = '';
        while (!feof($buffer)) {
            $data .= fread($buffer, 4096);
        }
        fclose($buffer);

        return (object)['code' => $code, 'data' => $data];
    }

    /**
     * Handle a login request.
     *
     * @param Request $request
     *
     * @return mixed
     */
    public function login(Request $request)
    {

        $data = $request->all();

        $rules = [
            'username' => 'required',
            'password' => 'required',
        ];
        Validator::make($data, $rules)->validate();

        $credentials = $request->only(['username', 'password']);
        $remember = $request->get('remember', false);

        if(config('admin.auth.captcha')) {
            $captcha = $request->session()->pull('captcha', '');

            if($request->input('captcha') != $captcha) {
                return [
                    'code' => 1, 
                    'msg' => trans('admin.login.error.captcha')
                ];
            }
        } 

        if (AuthService::attempt($credentials, $remember)) {
            return [
                'code' => 0, 
                'msg' => '', 
            ];
        }

        return [
            'code' => 1, 
            'msg' => trans('admin.login.error.username.or.password')
        ];
    }

    /**
     * Show the profile page.
     *
     * @return Redirector|RedirectResponse|View|Factory
     */
    public function profile()
    {
        if (AuthService::guest()) {

            $prefix = config('admin.route.prefix');

            // redirect to root path
            return redirect('/' . $prefix);
        }

        $user = AuthService::user();

        return admin_view('auth/profile', ['user' => $user]);
    }

    /**
     * User logout.
     *
     * @return mixed
     */
    public function logout(Request $request)
    {
        AuthService::logout();

        $request->session()->invalidate();

        $prefix = config('admin.route.prefix');

        $redirectTo = config('admin.auth.redirect_to');

        return redirect()->to($prefix . $redirectTo);
    }
}
